# Generated by Django 4.2 on 2023-04-21 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BestMovies_api', '0004_movie_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='liked_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='preview',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
