# Generated by Django 4.2 on 2023-04-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestMovies_api', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
